version: '3.1'

services:
  db:
    container_name: okta-restaurants
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3389:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: okta-restaurants
      MYSQL_USER: user
      MYSQL_PASSWORD: password
